edit yaml11

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -52,7 +52,7 @@ jobs:
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
-        ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
+        ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"
 
     - name: Pull Docker image from DockerHub on remote server
       run: |
